spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
  data:
    web:
      pageable:
        default-page-size: 10
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
    store-type: jdbc
  profiles:
    include: oauth
# mustache 한글 깨짐 방지
server:
  servlet:
    encoding:
      force-response: true
