spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
  data:
    web:
      pageable:
        default-page-size: 10

# mustache 한글 깨짐 방지
server:
  servlet:
    encoding:
      force-response: true
