# ec2에서 구동될 환경
spring:
  profiles:
    include: ec2, oauth, ec2-db
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL5InnoDBDialect
          storage_engine: innodb
  session:
    store-type: jdbc