server:
  port: 8081
spring:
  profiles:
    include: ec2-nginx1, oauth, ec2-db
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL5InnoDBDialect
          storage_engine: innodb
  session:
    store-type: jdbc
