spring:
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL5InnoDBDialect
          storage_engine: innodb
        show_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
    store-type: jdbc
  profiles:
    include: oauth
# mustache 한글 깨짐 방지
server:
  servlet:
    encoding:
      force-response: true
